Support more bond options
linux-system-roles/network pull request #452
Opened 2022-02-03 19:18 UTC by liangwen12year

In order to enable user to flexibly control the network transmission
over the bonded interface, support all the bond options which are
currently supported by NetworkManager.

Signed-off-by: Wen Liang <liangwen12year@gmail.com>

2022-02-03 19:18 UTC, liangwen12year commented
I will add the documentation soon.

2022-02-08 13:15 UTC, ffmancera requested changes
The code looks quite good! I made some comments, thanks!

2022-02-08 13:15 UTC, ffmancera commented on module_utils/network_lsr/argument_validator.py
> +                "the bond option primary is only valid with mode active-backup, balance-tlb, balance_alb",
nit: it should be `balance-alb` instead.

2022-02-08 15:55 UTC, liangwen12year commented
[citest bad]

2022-02-09 15:30 UTC, thom311 commented on module_utils/network_lsr/argument_validator.py
> +        if result["num_grat_arp"] != result["num_unsol_na"]:
for kernel, there are no two such options. And for NM,it will also just honor one.

No need to have both in the API.

2022-02-09 17:28 UTC, thom311 submitted a review, later dismissed

2022-02-09 22:00 UTC, ffmancera approved these changes

2022-02-10 10:41 UTC, ffmancera commented
[citest bad]

2022-02-10 15:10 UTC, ffmancera requested changes
This is breaking bond with initscripts because it is validating the properties incorrectly

```
MSG:

error: connection[0]: initscripts only supports the mode and miimon bond options. All the other bond options are not supported by initscripts.
META: 
```

2022-02-11 13:04 UTC, thom311 approved these changes

2022-02-11 17:22 UTC, tyll requested changes
There are too many mentions of "slave" in the README. Please remove them.

2022-02-11 17:31 UTC, tyll commented on README.md
> +    This option defines which slave is the primary device.
```suggestion
    This option defines the primary port.
```

2022-02-11 19:19 UTC, liangwen12year commented on README.md
> +    This option defines which slave is the primary device.
I updated. Thanks.

2022-02-11 19:28 UTC, tyll reviewed
There is once instance left

2022-02-11 19:28 UTC, tyll commented on README.md
> +    The possible values are: `none`, `active`, `follow`.
```suggestion
    This option specifies the policy to select the MAC address for the bond interface in active-backup mode. 
    The possible values are: `none` (default), `active`, `follow`.
```

2022-02-11 20:04 UTC, liangwen12year commented on README.md
> +    The possible values are: `none`, `active`, `follow`.
Thanks. I updated again.

2022-02-11 21:01 UTC, tyll approved these changes

2022-02-11 22:40 UTC, merged