Adding macVtap.yml in examples directory
linux-system-roles/network pull request #679
Opened 2024-03-14 01:16 UTC by marituhone

Enhancement:created separate macVtap.yml 

Reason:Providing example for MAC VTAP #285

Result:

Issue Tracker Tickets (Jira or BZ if any):

2024-03-14 13:58 UTC, ffmancera requested changes

2024-03-14 13:58 UTC, ffmancera commented on examples/macvtap.yml
> +- name: Manage network MAC VLAN
It should be `Manage network MAC VTAP` I think

2024-03-15 02:40 UTC, liangwen12year commented
`PR Title lint` is failed, you can take a look at https://linux-system-roles.github.io/contribute.html, specifically the section about `Write a good PR title and description`. In short, you can change the title into `docs: Add MAC VTAP example`.

2024-03-15 14:10 UTC, liangwen12year commented
Can you squash the PR into only one commit with the commit title `docs: Add MAC VTAP example`.

2024-03-19 13:41 UTC, spetrosi commented
> Can you squash the PR into only one commit with the commit title `docs: Add MAC VTAP example`.

fyi, we moved the requirement to indicate change type to the PR title only. Commits now can be in any form. Though I like to still add a `type:` prefix to the commit for clarity.

2024-03-21 16:15 UTC, liangwen12year commented
https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec, please look at this guide on how to squash the commits.

2024-03-24 20:49 UTC, marituhone commented
@liangwen12year  i did squash them

2024-03-25 01:09 UTC, liangwen12year commented
> @liangwen12year i squashed them

Can you check why the pr also has the commit - `Merge branch 'linux-system-roles:main' into issueFix` ?

2024-03-26 08:04 UTC, marituhone commented
@liangwen12year  i fix it

2024-03-26 19:11 UTC, liangwen12year approved these changes

2024-03-26 19:12 UTC, liangwen12year commented
> @liangwen12year i have fixed it

@marituhone thanks for contributing to it.

2024-03-26 21:14 UTC, liangwen12year commented
Nit-picking, can you change the commit title to `docs: Add MAC VTAP example`?

2024-03-28 17:21 UTC, richm approved these changes

2024-03-28 17:22 UTC, merged